// Created by Crowbar 0.74

$modelname "vm_jup_cp08_br_xmike5_pgrip_tac_000_LOD0.mdl"

$bodygroup "slide"
{
	studio "vm_jup_cp08_br_xmike5_pgrip_tac_000_LOD0.smd"
}


$surfaceprop "default"

$contents "solid"

$illumposition 0 0 0

$mostlyopaque


$cdmaterials "zeron/weapons/basp/"

$cbox 0 0 0 0 0 0

$bbox -9.147 -1.396 -4.275 0 1.389 0.638



$sequence "reference" {
	"vm_jup_cp08_br_xmike5_pgrip_tac_000_LOD0.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$keyvalues
{
// CSGO compiler adds the qc_path keyvalue section automatically.
//	qc_path 
//	{
//		"value" "g:\other\gmod\source-files-mw\attachments\mike4\attachment_stock.qc"
//	}
}
