// Created by Crowbar 0.74

$modelname "wm_jup_cp08_br_xmike5_mag_45_277f_000_LOD0.mdl"

$bodygroup "grip"
{
	studio "wm_jup_cp08_br_xmike5_mag_45_277f_000_LOD0.smd"
}

$surfaceprop "default"

$contents "solid"

$illumposition 0 0 0

$mostlyopaque

$cdmaterials "zeron/weapons/basp/"
$cbox 0 0 0 0 0 0

$bbox -2.631 -0.554 -5.726 0.841 0.548 1.99


$sequence "reference" {
	"wm_jup_cp08_br_xmike5_mag_45_277f_000_LOD0.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$keyvalues
{
// CSGO compiler adds the qc_path keyvalue section automatically.
//	qc_path 
//	{
//		"value" "c:\github\source files mw\source-files-mw\attachments\assault rifles\mike4\attachment_mag.qc"
//	}
}

