/*
* Advanced weighting script X
* Wraith - Game extraction tools
*/

global proc WraithMesh_5602c67c_00_BindFunc()
{
   select -r WraithMesh_5602c67c_00;
   select -add tag_origin;
   newSkinCluster "-toSelectedBones -mi 15 -omi true -dr 5.0 -rui false";   string $clu = findRelatedSkinCluster("WraithMesh_5602c67c_00");

   skinPercent -tv tag_origin 1.0 $clu WraithMesh_5602c67c_00.vtx[0:9281];
}

global proc WraithMesh_5602c67c_01_BindFunc()
{
   select -r WraithMesh_5602c67c_01;
   select -add tag_origin;
   newSkinCluster "-toSelectedBones -mi 15 -omi true -dr 5.0 -rui false";   string $clu = findRelatedSkinCluster("WraithMesh_5602c67c_01");

   skinPercent -tv tag_origin 1.0 $clu WraithMesh_5602c67c_01.vtx[0:11773];
}

global proc WraithMesh_5602c67c_02_BindFunc()
{
   select -r WraithMesh_5602c67c_02;
   select -add tag_origin;
   newSkinCluster "-toSelectedBones -mi 15 -omi true -dr 5.0 -rui false";   string $clu = findRelatedSkinCluster("WraithMesh_5602c67c_02");

   skinPercent -tv tag_origin 1.0 $clu WraithMesh_5602c67c_02.vtx[0:16306];
}

global proc WraithMesh_5602c67c_03_BindFunc()
{
   select -r WraithMesh_5602c67c_03;
   select -add tag_origin;
   newSkinCluster "-toSelectedBones -mi 15 -omi true -dr 5.0 -rui false";   string $clu = findRelatedSkinCluster("WraithMesh_5602c67c_03");

   skinPercent -tv tag_origin 1.0 $clu WraithMesh_5602c67c_03.vtx[0:6625];
}

global proc WraithMesh_5602c67c_04_BindFunc()
{
   select -r WraithMesh_5602c67c_04;
   select -add tag_origin;
   newSkinCluster "-toSelectedBones -mi 15 -omi true -dr 5.0 -rui false";   string $clu = findRelatedSkinCluster("WraithMesh_5602c67c_04");

   skinPercent -tv tag_origin 1.0 $clu WraithMesh_5602c67c_04.vtx[0:5135];
}

global proc WraithMesh_5602c67c_05_BindFunc()
{
   select -r WraithMesh_5602c67c_05;
   select -add tag_origin;
   newSkinCluster "-toSelectedBones -mi 15 -omi true -dr 5.0 -rui false";   string $clu = findRelatedSkinCluster("WraithMesh_5602c67c_05");

   skinPercent -tv tag_origin 1.0 $clu WraithMesh_5602c67c_05.vtx[0:619];
}

global proc WraithMesh_5602c67c_06_BindFunc()
{
   select -r WraithMesh_5602c67c_06;
   select -add tag_origin;
   newSkinCluster "-toSelectedBones -mi 15 -omi true -dr 5.0 -rui false";   string $clu = findRelatedSkinCluster("WraithMesh_5602c67c_06");

   skinPercent -tv tag_origin 1.0 $clu WraithMesh_5602c67c_06.vtx[0:653];
}

global proc WraithMesh_5602c67c_07_BindFunc()
{
   select -r WraithMesh_5602c67c_07;
   select -add tag_origin;
   newSkinCluster "-toSelectedBones -mi 15 -omi true -dr 5.0 -rui false";   string $clu = findRelatedSkinCluster("WraithMesh_5602c67c_07");

   skinPercent -tv tag_origin 1.0 $clu WraithMesh_5602c67c_07.vtx[0:7586];
}

global proc WraithMesh_5602c67c_08_BindFunc()
{
   select -r WraithMesh_5602c67c_08;
   select -add tag_origin;
   newSkinCluster "-toSelectedBones -mi 15 -omi true -dr 5.0 -rui false";   string $clu = findRelatedSkinCluster("WraithMesh_5602c67c_08");

   skinPercent -tv tag_origin 1.0 $clu WraithMesh_5602c67c_08.vtx[0:1064];
}

global proc WraithMesh_5602c67c_09_BindFunc()
{
   select -r WraithMesh_5602c67c_09;
   select -add tag_origin;
   newSkinCluster "-toSelectedBones -mi 15 -omi true -dr 5.0 -rui false";   string $clu = findRelatedSkinCluster("WraithMesh_5602c67c_09");

   skinPercent -tv tag_origin 1.0 $clu WraithMesh_5602c67c_09.vtx[0:896];
}

global proc WraithMesh_5602c67c_10_BindFunc()
{
   select -r WraithMesh_5602c67c_10;
   select -add tag_origin;
   newSkinCluster "-toSelectedBones -mi 15 -omi true -dr 5.0 -rui false";   string $clu = findRelatedSkinCluster("WraithMesh_5602c67c_10");

   skinPercent -tv tag_origin 1.0 $clu WraithMesh_5602c67c_10.vtx[0:2008];
}

global proc WraithMesh_5602c67c_11_BindFunc()
{
   select -r WraithMesh_5602c67c_11;
   select -add tag_origin;
   newSkinCluster "-toSelectedBones -mi 15 -omi true -dr 5.0 -rui false";   string $clu = findRelatedSkinCluster("WraithMesh_5602c67c_11");

   skinPercent -tv tag_origin 1.0 $clu WraithMesh_5602c67c_11.vtx[0:482];
}

global proc WraithMesh_5602c67c_12_BindFunc()
{
   select -r WraithMesh_5602c67c_12;
   select -add tag_origin;
   newSkinCluster "-toSelectedBones -mi 15 -omi true -dr 5.0 -rui false";   string $clu = findRelatedSkinCluster("WraithMesh_5602c67c_12");

   skinPercent -tv tag_origin 1.0 $clu WraithMesh_5602c67c_12.vtx[0:1678];
}

global proc RunAdvancedScript()
{
   catch(WraithMesh_5602c67c_00_BindFunc());
   catch(WraithMesh_5602c67c_01_BindFunc());
   catch(WraithMesh_5602c67c_02_BindFunc());
   catch(WraithMesh_5602c67c_03_BindFunc());
   catch(WraithMesh_5602c67c_04_BindFunc());
   catch(WraithMesh_5602c67c_05_BindFunc());
   catch(WraithMesh_5602c67c_06_BindFunc());
   catch(WraithMesh_5602c67c_07_BindFunc());
   catch(WraithMesh_5602c67c_08_BindFunc());
   catch(WraithMesh_5602c67c_09_BindFunc());
   catch(WraithMesh_5602c67c_10_BindFunc());
   catch(WraithMesh_5602c67c_11_BindFunc());
   catch(WraithMesh_5602c67c_12_BindFunc());
}

global proc NamespacePurge()
{
   string $allNodes[] = `ls`;
   for($node in $allNodes) {
      string $buffer[];
      tokenize $node ":" $buffer;
      string $newName = $buffer[size($buffer)-1];
       catchQuiet(`rename $node $newName`);
   }
}

print("Currently binding the current model, please wait...\n");
NamespacePurge();
RunAdvancedScript();
print("The model has been binded.\n");

